SIGPIP/Controllers/StudentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SIGPIP.Context;
using SIGPIP.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SIGPIP.Controllers
{
    public class StudentController : Controller
    {
        private readonly DatabaseContext _databaseContext;

        public StudentController(DatabaseContext databaseContext)
        {
            this._databaseContext = databaseContext;
        }

        public bool LoggedInVerify()
        {
            return (HttpContext.Session.GetString("loggedIn") == null ? false : true);
        }

        public IActionResult Report()
        {
            if (LoggedInVerify() == false)
            {
                return RedirectToAction("Login");
            }
            else
            {
                try
                {
                    var studentIdLogged = Guid.Parse(HttpContext.Session.GetString("studentIdLogged"));

                    List<ProjectModel> studentProjects = _databaseContext.Project.Where(p => p.studentId == studentIdLogged).ToList();

                    ViewBag.studentName = HttpContext.Session.GetString("studentName");
                    ViewBag.studentIdLogged = HttpContext.Session.GetString("studentIdLogged");
                    ViewBag.studentEmail = HttpContext.Session.GetString("studentEmail");
                    ViewBag.projects = this.GetProject(HttpContext.Session.GetString("studentIdLogged"));
                    return View(studentProjects);

                }
                catch (Exception ex)
                {
                    return NotFound();
                }
            }
        }

        public IActionResult Home()
        {
            if (LoggedInVerify() == false)
            {
                return RedirectToAction("Login");
            }
            else
            {
                try
                {
                    var studentIdLogged = Guid.Parse(HttpContext.Session.GetString("studentIdLogged"));

                    List<ProjectModel> studentProjects = _databaseContext.Project.Where(p => p.studentId == studentIdLogged).ToList();

                    ViewBag.studentName = HttpContext.Session.GetString("studentName");
                    ViewBag.studentIdLogged = HttpContext.Session.GetString("studentIdLogged");
                    ViewBag.studentEmail = HttpContext.Session.GetString("studentEmail");
                    return View(studentProjects);
                    
                }
                catch (Exception ex)
                {
                    return NotFound();
                }
            }
        }

        public IActionResult Login()
        {
            return View();
        }

        /*Login Method Here*/
        [HttpPost]
        public IActionResult Login(StudentModel students)
        {
            string studentsHashPass = Encryption.EnryptString(students.studentPassword);
            var studentLoggedIn = _databaseContext.Student.SingleOrDefault(std => std.studentEmail == students.studentEmail && std.studentPassword == studentsHashPass);
            if (studentLoggedIn != null)
            {
                HttpContext.Session.SetString("studentIdLogged", studentLoggedIn.studentId.ToString());
                HttpContext.Session.SetString("studentName", studentLoggedIn.studentNames);
                HttpContext.Session.SetString("studentLastName", studentLoggedIn.studentLastNames);
                HttpContext.Session.SetString("studentCountry", studentLoggedIn.studentCountry);
                HttpContext.Session.SetString("studentCareer", studentLoggedIn.studentCareer);
                HttpContext.Session.SetString("studentSemester", studentLoggedIn.studentSemester.ToString());
                HttpContext.Session.SetString("studentEmail", studentLoggedIn.studentEmail);
                if (studentLoggedIn.studentBio != null)
                {
                    HttpContext.Session.SetString("studentBio", studentLoggedIn.studentBio);
                }
                else
                {
                    HttpContext.Session.SetString("studentBio", "");
                }
                HttpContext.Session.SetString("loggedIn", "logged");

                return RedirectToAction("Home");
            }
            else
            {
                TempData["errorLogin"] = "This user does not exist or check the information";
                return View();
            }
        }

        public bool EmailExistenceValidation(string emailStudent)
        {
            var existenceEmail = _databaseContext.Student.SingleOrDefault(std => std.studentEmail == emailStudent);
            return existenceEmail == null ? false : true;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(StudentModel student)
        {
            string pass = student.studentPassword;
            string cpass = student.studentConfirmPassword;

            if (ModelState.IsValid)
            {
                if (pass == cpass)
                {
                    if (EmailExistenceValidation(student.studentEmail) == true)
                    {
                        TempData["emailExists"] = "Email already exists!";
                    }
                    else
                    {
                        try
                        {
                            Guid _studentId = Guid.NewGuid();
                            string hashPass = Encryption.EnryptString(pass);

                            StudentModel studentModel = new StudentModel()
                            {
                                studentId = _studentId,
                                studentNames = student.studentNames,
                                studentLastNames = student.studentLastNames,
                                studentBio = student.studentBio,
                                studentCareer = student.studentCareer,
                                studentCountry = student.studentCountry,
                                studentEmail = student.studentEmail,
                                studentPassword = hashPass,
                                studentConfirmPassword = hashPass,
                                studentSemester = student.studentSemester
                            };
                            HttpContext.Session.SetString("nowStudentId", studentModel.studentId.ToString());
                            _databaseContext.Student.Add(studentModel);
                            _databaseContext.SaveChanges();
                            TempData["successRegister"] = "Account created successfully!";
                            return RedirectToAction("Login", studentModel);
                        }
                        catch (Exception ex)
                        {
                            TempData["errorRegister"] = ex;
                        }
                    }

                }
            }
            else
            {
                TempData["errorRegister"] = "Account could not be created";
            }
            return View();
        }

        [HttpGet]
        public IActionResult GetStudent()
        {
            try
            {
                var students = _databaseContext.Student.ToList();
                return Ok(students);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        public IActionResult UpdateStudent(Guid studentId)
        {
            if (studentId == null)
            {
                return (NotFound());
            }
            var student = _databaseContext.Student.Find(studentId);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        [HttpPost]
        public IActionResult UpdateStudent(Guid studentId, StudentModel student1)
        {
            StudentModel studentModel = _databaseContext.Student.FirstOrDefault(student => student.studentId == studentId);
            if (studentModel != null)
            {
                try
                {
                    studentModel.studentNames = student1.studentNames;
                    studentModel.studentLastNames = student1.studentLastNames;
                    studentModel.studentCountry = student1.studentCountry;
                    studentModel.studentCareer = student1.studentCareer;
                    studentModel.studentSemester = student1.studentSemester;
                    studentModel.studentEmail = student1.studentEmail;
                    studentModel.studentBio = student1.studentBio;
                    _databaseContext.Student.Update(studentModel);
                    _databaseContext.SaveChanges();
                    HttpContext.Session.SetString("studentIdLogged", studentModel.studentId.ToString());
                    HttpContext.Session.SetString("studentName", studentModel.studentNames);
                    HttpContext.Session.SetString("studentLastName", studentModel.studentLastNames);
                    HttpContext.Session.SetString("studentCountry", studentModel.studentCountry);
                    HttpContext.Session.SetString("studentCareer", studentModel.studentCareer);
                    HttpContext.Session.SetString("studentSemester", studentModel.studentSemester.ToString());
                    HttpContext.Session.SetString("studentEmail", studentModel.studentEmail);
                    if (studentModel.studentBio != null)
                    {
                        HttpContext.Session.SetString("studentBio", studentModel.studentBio);
                    }
                    else
                    {

SIGPIP/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;

namespace SIGPIP.Controllers
{
    public class TeamController : Controller
    {
        public IActionResult Members()
        {
            return View("Members");
        }
    }
}

SIGPIP/Views/Student/Login.cshtml
@model SIGPIP.Models.StudentModel

@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_LayoutLoginRegister.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="~/css/styleLogin.css"/>
}

@section Nav{
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
          <a class="navbar-brand" href="#">SIGPIP</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                  <a class="dropdown-item" asp-controller="Team" asp-action="Members">Team</a>
                  <a href="https://github.com/SIGPIP/SIGPIP" target="_blank" class="dropdown-item">Github</a>
                </div>
              </li>
            </ul>
          </div>
        </nav>
}

<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
							<div class="text w-100">
								<h2>Welcome to SIGPIP</h2>
								<p>Don't have an account?</p>
								<a asp-action="Register" class="btn btn-white btn-outline-white">Register</a>
							</div>
			            </div>
						<div class="login-wrap p-4 p-lg-5">
			      	        <div class="d-flex">
			      		    <div class="w-100">
			      			    <h3 class="mb-4">Login</h3>
			      		    </div>
			      	    </div>
				    <form  autocomplete="off" asp-action="Login" class="signin-form">
			      		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
     
                        <div class="form-group">
                            <label asp-for="studentEmail" class="control-label">Email</label>
                            <input asp-for="studentEmail" placeholder="Email" class="form-control" />
                            <span asp-validation-for="studentEmail" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="studentPassword" class="control-label">Password</label>
                            <input asp-for="studentPassword" placeholder="Password" class="form-control" />
                            <span asp-validation-for="studentPassword" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="form-control btn btn-primary submit px-3" />
                        </div>
		          </form>
		        </div>
		      </div>
				</div>
			</div>
		</div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

     @if (TempData["errorLogin"] != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    swal("Error!", '@TempData["errorLogin"]', "error");
                };
            </script>
        }

        @if (TempData["successRegister"] != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    swal("Congrats!", '@TempData["successRegister"]', "success");
                };
            </script>
        }
}

SIGPIP/Views/Student/Register.cshtml
@model SIGPIP.Models.StudentModel

@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_LayoutLoginRegister.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="~/css/styleRegister.css"/>
}

@section Nav{
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
          <a class="navbar-brand" href="#">SIGPIP</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" asp-controller="Team" asp-action="Members">Team</a>
                  <a href="https://github.com/SIGPIP/SIGPIP" target="_blank" class="dropdown-item">Github</a>
                </div>
              </li>
            </ul>
            <form class="form-inline my-2 my-md-0">
              <a asp-controller="Student" asp-action="Login" class="btn btn-primary">Login</a>
            </form>
          </div>
        </nav>
}

<!--
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="studentNames" class="control-label"></label>
                <input asp-for="studentNames" class="form-control" />
                <span asp-validation-for="studentNames" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentLastNames" class="control-label"></label>
                <input asp-for="studentLastNames" class="form-control" />
                <span asp-validation-for="studentLastNames" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentEmail" class="control-label"></label>
                <input asp-for="studentEmail" class="form-control" />
                <span asp-validation-for="studentEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentPassword" class="control-label"></label>
                <input asp-for="studentPassword" class="form-control" />
                <span asp-validation-for="studentPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentConfirmPassword" class="control-label"></label>
                <input asp-for="studentConfirmPassword" class="form-control" />
                <span asp-validation-for="studentConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentBio" class="control-label"></label>
                <input asp-for="studentBio" class="form-control" />
                <span asp-validation-for="studentBio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentCareer" class="control-label"></label>
                <input asp-for="studentCareer" class="form-control" />
                <span asp-validation-for="studentCareer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentSemester" class="control-label"></label>
                <input asp-for="studentSemester" class="form-control" />
                <span asp-validation-for="studentSemester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="studentCountry" class="control-label"></label>
                <input asp-for="studentCountry" class="form-control" />
                <span asp-validation-for="studentCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Login">Login</a>
</div>
-->

<section>
  <div class="mask d-flex align-items-center">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-left mb-4">Register</h2>
              <form method="POST" asp-action="Register" autocomplete="off">
                <div class="row">
                    <div class="form-group col">
                        <label asp-for="studentNames" class="control-label"></label>
                        <input asp-for="studentNames" class="form-control" />
                        <span asp-validation-for="studentNames" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="studentLastNames" class="control-label"></label>
                        <input asp-for="studentLastNames" class="form-control" />
                        <span asp-validation-for="studentLastNames" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col">
                        <label asp-for="studentEmail" class="control-label"></label>
                        <input asp-for="studentEmail" class="form-control" />
                        <span asp-validation-for="studentEmail" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col">
                        <label asp-for="studentPassword" class="control-label"></label>
                        <input asp-for="studentPassword" class="form-control" />
                        <span asp-validation-for="studentPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="studentConfirmPassword" class="control-label"></label>
                        <input asp-for="studentConfirmPassword" class="form-control" />
                        <span asp-validation-for="studentConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col">
                        <label asp-for="studentCareer" class="control-label"></label>
                        <input asp-for="studentCareer" class="form-control" />
                        <span asp-validation-for="studentCareer" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col">
                        <label asp-for="studentSemester" class="control-label"></label>
                        <input asp-for="studentSemester" class="form-control" />
                        <span asp-validation-for="studentSemester" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="studentCountry" class="control-label"></label>
                        <input asp-for="studentCountry" class="form-control" />
                        <span asp-validation-for="studentCountry" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col">
                        <label asp-for="studentBio" class="control-label"></label>
                        <input asp-for="studentBio" class="form-control" type="textarea"/>
                        <span asp-validation-for="studentBio" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col">
                        <input type="submit" value="Register" class="btn btn-primary" />
                    </div> 
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    @if (TempData["errorRegister"] != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    swal("Error!", '@TempData["errorRegister"]', "error");
                };
            </script>
        }

     @if (TempData["emailExists"] != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    swal("Error!", '@TempData["emailExists"]', "error");
                };
            </script>
        }
}