SIGPIP/Controllers/StudyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SIGPIP.Context;
using SIGPIP.Models;
using System;
using System.Linq;

namespace SIGPIP.Controllers
{
    public class StudyController : Controller
    {
        private readonly DatabaseContext _databaseContext;

        public StudyController(DatabaseContext databaseContext)
        {
            this._databaseContext = databaseContext;
        }

        [HttpPost]
        public IActionResult AddStudy(StudyModel study)
        {
            StudyModel studyModel1 = _databaseContext.Study.FirstOrDefault(study1 => study1.studyId == study.studyId);
            if (studyModel1 == null) 
            { 
                try
                {
                    Guid _studyId = Guid.NewGuid();
                    StudyModel studyModel = new StudyModel()
                    {
                        studyId = _studyId,
                        studentId =study.studentId,
                        studyYear = study.studyYear,
                        studyGrade = study.studyGrade,
                        studyName = study.studyName,
                        studyPlace = study.studyPlace,
                        studyCity = study.studyCity,
                        studyCountry = study.studyCountry
                    };
                    _databaseContext.Study.Add(studyModel);
                    _databaseContext.SaveChanges();
                    TempData["successStudyAdd"] = "Study added successfully!";
                    return RedirectToAction("Portfolio","Student");
                }
                catch (Exception ex)
                {
                    TempData["errorStudyAdd"] = ex;
                }
                return RedirectToAction("Portfolio","Student");
            }
            else
            {
                return UpdateStudy(study.studyId, study);
            }
        }

        [HttpGet]
        public IActionResult GetStudy()
        {
            try
            {
                var list = _databaseContext.Study;
                return View(list);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        public IActionResult UpdateStudy(Guid studyId)
        {
            if (studyId == null)
            {
                return (NotFound());
            }
            var study = _databaseContext.Study.Find(studyId);
            if (study == null)
            {
                return NotFound();
            }

            return View(study);
        }

        [HttpPost]
        public IActionResult UpdateStudy(Guid studyId, StudyModel study1)
        {
            StudyModel studyModel = _databaseContext.Study.FirstOrDefault(study => study.studyId == studyId);
            if (studyModel != null)
            {
                try
                {
                    studyModel.studyYear = study1.studyYear;
                    studyModel.studyGrade = study1.studyGrade;
                    studyModel.studyName = study1.studyName;
                    studyModel.studyPlace = study1.studyPlace;
                    studyModel.studyCity = study1.studyCity;
                    studyModel.studyCountry = study1.studyCountry;
                    _databaseContext.Study.Update(studyModel);
                    _databaseContext.SaveChanges();
                    TempData["successUpdatingStudy"] = "Study updated successfully!";
                }
                catch (Exception ex)
                {
                    TempData["errorUpdatingStudy"] = ex;
                }
            }
            else
            {
                TempData["errorUpdatingStudy"] = "Study could not be updated";
            }
            return RedirectToAction("Portfolio","Student");
        }
        [HttpGet]
        public IActionResult DeleteStudy(Guid studyId)
        {
            try
            {
                StudyModel studyModel = _databaseContext.Study.FirstOrDefault(study => study.studyId == studyId);

                if (studyModel != null)
                {
                    _databaseContext.Study.Remove(studyModel);
                    _databaseContext.SaveChanges();
                    TempData["successDeletingStudy"] = "Study deleted successfully!";
                    return View("Home");
                }
                else
                {
                    TempData["errorDeletingStudy"] = "Study could not be deleted";
                }
            }
            catch (Exception ex)
            {
                TempData["errorDeletingStudy"] = ex;
            }
            return RedirectToAction("Portfolio", "Student");
        }
    }
}

SIGPIP/Views/Study/GetStudy.cshtml
@model SIGPIP.Models.StudyModel

@{
    ViewData["Title"] = "GetStudy";
}

<div class="box-header with-border">
    <h3 class="box-title">Education</h3>
    <button id="btnAddStudy" class="btn" onclick="addForm.hidden=false; btnAddStudy.hidden=!btnAddStudy.hidden;"> <i class="fas fa-plus"></i></button>
    <ul class="box-controls pull-right">

        <li><a class="box-btn-slide" href="#"></a></li>
    </ul>
</div>
<div class="box-body">
    <div class="col-12">
        <div>
            <table class="table" col-12 style="display: block; overflow-x: auto; white-space: nowrap;">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Grade
                        </th>
                        <th>
                            Year
                        </th>
                        <th>
                            Place
                        </th>
                        <th>
                            Country
                        </th>
                        <th>
                            City
                        </th>
                    </tr>
                </thead>
                <tbody>
                @foreach (StudyModel item in @ViewBag.studies)
                {
                    <tr>
                        <td>
                            @item.studyName
                        </td>
                        <td>
                            @item.studyGrade
                        </td>
                        <td>
                            @item.studyYear
                        </td>
                        <td>
                            @item.studyPlace
                        </td>
                        <td>
                            @item.studyCountry
                        </td>
                        <td>
                            @item.studyCity
                        </td>
                        <td align="right" style="max-width: 4rem;">
                            <button type="button" class="btn btn-outline-primary" onclick="newBtn.hidden=false; AddBtn.value='Edit'; addForm.hidden=false; btnAddStudy.hidden=true; studyId.value='@item.studyId'; studyName.value='@item.studyName'; studyGrade.value='@item.studyGrade'; studyYear.value='@item.studyYear'; studyPlace.value='@item.studyPlace'; studyCountry.value='@item.studyCountry'; studyCity.value='@item.studyCity'">Edit</button>
                            <a type="button" class="btn btn-outline-danger" asp-action="DeleteStudy" asp-route-studyId="@item.studyId" asp-controller="Study">Delete</a>
                        </td>   
                    </tr>
                }
                </tbody>
                </table>
        </div>
            <form asp-controller="Study" asp-action="AddStudy" id="addForm" hidden method="post">
            <div asp-validation-summary="ModelOnly"  class="text-danger"></div>
            <input type="hidden" asp-for="studyId" id="studyId" />
            <input type="hidden" asp-for="studentId" value=@ViewBag.studentIdLogged />
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="studyName" class="control-label required">Name</label>
                        <input asp-for="studyName" class="form-control" id="studyName" />
                        <span asp-validation-for="studyName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="studyGrade" class="control-label required">Grade</label>
                        <input asp-for="studyGrade" class="form-control" id="studyGrade" />
                        <span asp-validation-for="studyGrade" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="studyYear" class="control-label required">Year</label>
                        <input asp-for="studyYear" class="form-control" id="studyYear"/>
                        <span asp-validation-for="studyYear" class="text-danger"></span>
                    </div>
                </div>    
            </div>
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="studyPlace" class="control-label required">Place</label>
                        <input asp-for="studyPlace" class="form-control" id="studyPlace" />
                        <span asp-validation-for="studyPlace" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="studyCountry" class="control-label">Country</label>
                        <input asp-for="studyCountry" class="form-control" id="studyCountry"/>
                        <span asp-validation-for="studyCountry" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="studyCity" class="control-label">City</label>
                        <input asp-for="studyCity" class="form-control" id="studyCity"/>
                        <span asp-validation-for="studyCity" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div>
                <p>Text area with * are mandatory</p>
            </div>
            <div class="row justify-content-between">
                <div class="col-auto mr-auto">
                    <input type="submit" value="Add" id="AddBtn" class="btn btn-outline-success" />
                </div>
                <div class="col-auto mr-auto">
                    <input type="button" value="Add New" hidden id="newBtn" class="btn btn-outline-primary" onclick="newBtn.hidden=true; AddBtn.value='Add'; studyId.value=''; studyName.value=''; studyGrade.value=''; studyYear.value=''; studyPlace.value=''; studyCountry.value=''; studyCity.value='';" />
                </div>
                <div class="col-auto">
                    <input type="button" id="cancelStudy" value="Cancel" class="btn btn-outline-dark" onclick="window.location.reload()"/>
                </div>
            </div>
        </form>
    </div> 
</div>